from __future__ import annotations

import html
import json
import re
from html.parser import HTMLParser
from pathlib import Path

from markdown_it import MarkdownIt

from .files import DocFile, copy_binary, iter_asset_files, load_doc, load_docs, safe_write
from .inspector import inspect_doc
from .pdf import write_simple_pdf


STYLE = """
:root {
  color-scheme: light;
  --bg: #fafafa;
  --panel: #ffffff;
  --text: #1f2937;
  --muted: #667085;
  --line: #d7dde5;
  --accent: #0f766e;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--bg);
  color: var(--text);
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  line-height: 1.65;
}
.layout { display: grid; grid-template-columns: 280px minmax(0, 1fr); min-height: 100vh; }
nav {
  background: #eef2f1;
  border-right: 1px solid var(--line);
  padding: 24px 18px;
  position: sticky;
  top: 0;
  height: 100vh;
  overflow: auto;
}
nav h1 { font-size: 18px; margin: 0 0 18px; }
nav a { display: block; color: var(--text); text-decoration: none; padding: 6px 0; }
nav a:hover { color: var(--accent); }
main { max-width: 980px; width: 100%; padding: 44px 56px 80px; }
article {
  background: var(--panel);
  border: 1px solid var(--line);
  border-radius: 8px;
  padding: 36px 42px;
}
h1, h2, h3 { line-height: 1.25; }
a { color: var(--accent); }
code, pre { background: #f0f3f5; border-radius: 5px; }
code { padding: 2px 5px; }
pre { padding: 14px 16px; overflow: auto; }
table { border-collapse: collapse; width: 100%; }
td, th { border: 1px solid var(--line); padding: 8px 10px; text-align: left; }
.meta { color: var(--muted); font-size: 13px; margin-top: 28px; }
@media (max-width: 820px) {
  .layout { display: block; }
  nav { position: static; height: auto; border-right: 0; border-bottom: 1px solid var(--line); }
  main { padding: 24px 18px 48px; }
  article { padding: 24px 20px; }
}
"""


class TextExtractor(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.parts: list[str] = []

    def handle_data(self, data: str) -> None:
        if data.strip():
            self.parts.append(data.strip())

    def text(self) -> str:
        return "\n".join(self.parts)


def markdown_to_html(text: str) -> str:
    parser = MarkdownIt("commonmark", {"html": True, "linkify": True, "typographer": True}).enable("table")
    return parser.render(text)


def html_to_text(text: str) -> str:
    parser = TextExtractor()
    parser.feed(text)
    return parser.text()


def markdown_to_text(text: str) -> str:
    text = re.sub(r"```.*?```", "", text, flags=re.DOTALL)
    text = re.sub(r"`([^`]+)`", r"\1", text)
    text = re.sub(r"!\[([^\]]*)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"^#{1,6}\s*", "", text, flags=re.MULTILINE)
    text = re.sub(r"[*_~>#-]+", " ", text)
    return "\n".join(line.strip() for line in text.splitlines() if line.strip())


def doc_title(doc: DocFile) -> str:
    stats = inspect_doc(doc)
    if stats.headings:
        return stats.headings[0].title
    return doc.relative.stem.replace("-", " ").replace("_", " ").title()


def render_page(doc: DocFile, docs: list[DocFile]) -> str:
    nav = "\n".join(
        f'<a href="{html.escape(item.slug)}.html">{html.escape(doc_title(item))}</a>'
        for item in docs
    )
    if doc.path.suffix.lower() in {".html", ".htm"}:
        body = doc.text
    else:
        body = markdown_to_html(doc.text)
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html.escape(doc_title(doc))}</title>
  <link rel="stylesheet" href="assets/docsmith.css">
</head>
<body>
  <div class="layout">
    <nav>
      <h1>Documentation</h1>
      {nav}
    </nav>
    <main>
      <article>
        {body}
        <p class="meta">Generated by Docsmith.</p>
      </article>
    </main>
  </div>
</body>
</html>
"""


def build_site(path: str | Path, output: str | Path = "site", clean: bool = False) -> tuple[Path, list[Path]]:
    docs = load_docs(path)
    if not docs:
        raise ValueError("no documentation files found")

    target = Path(output).expanduser().resolve()
    if clean and target.exists():
        for item in sorted(target.rglob("*"), reverse=True):
            if item.is_file():
                item.unlink()
            elif item.is_dir():
                item.rmdir()
    target.mkdir(parents=True, exist_ok=True)
    assets_dir = target / "assets"
    assets_dir.mkdir(exist_ok=True)
    (assets_dir / "docsmith.css").write_text(STYLE.strip() + "\n", encoding="utf-8")

    written: list[Path] = []
    for doc in docs:
        output_file = target / f"{doc.slug}.html"
        output_file.parent.mkdir(parents=True, exist_ok=True)
        output_file.write_text(render_page(doc, docs), encoding="utf-8")
        written.append(output_file)

    first = target / "index.html"
    if first.resolve() != written[0].resolve():
        first.write_text(written[0].read_text(encoding="utf-8"), encoding="utf-8")
        written.append(first)

    root = Path(path).expanduser().resolve()
    if root.is_file():
        root = root.parent
    for asset in iter_asset_files(root, docs):
        destination = target / asset.relative_to(root)
        copy_binary(asset, destination)
    return target, written


def convert_file(source: str | Path, to_format: str, output: str | Path | None = None) -> Path:
    path = Path(source).expanduser().resolve()
    doc = load_doc(path)
    fmt = to_format.lower().strip(".")
    if fmt not in {"html", "md", "markdown", "txt", "text", "json", "pdf"}:
        raise ValueError("format must be one of html, md, txt, json, or pdf")

    target_suffix = "md" if fmt == "markdown" else "txt" if fmt == "text" else fmt
    target = Path(output).expanduser() if output else path.with_suffix(f".{target_suffix}")

    source_ext = path.suffix.lower()
    if fmt == "html":
        content = doc.text if source_ext in {".html", ".htm"} else markdown_to_html(doc.text)
        return safe_write(target, content)
    if fmt in {"txt", "text"}:
        content = html_to_text(doc.text) if source_ext in {".html", ".htm"} else markdown_to_text(doc.text)
        return safe_write(target, content)
    if fmt in {"md", "markdown"}:
        if source_ext in {".html", ".htm"}:
            title = path.stem.replace("-", " ").title()
            content = f"# {title}\n\n{html_to_text(doc.text)}\n"
        else:
            content = doc.text
        return safe_write(target, content)
    if fmt == "json":
        stats = inspect_doc(doc)
        content = json.dumps(
            {
                "path": str(doc.path),
                "title": doc_title(doc),
                "lines": stats.lines,
                "words": stats.words,
                "checksum": stats.checksum,
                "headings": [heading.__dict__ for heading in stats.headings],
                "links": [link.__dict__ for link in stats.links],
            },
            indent=2,
        )
        return safe_write(target, content + "\n")
    text = html_to_text(doc.text) if source_ext in {".html", ".htm"} else markdown_to_text(doc.text)
    return write_simple_pdf(target, doc_title(doc), text.splitlines())

